# Generated by Django 6.0.2 on 2026-03-06 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player_alter_game_id_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=20)),
                ('bet_value', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('result', models.CharField(blank=True, max_length=20)),
                ('spun_number', models.IntegerField(null=True)),
                ('payout', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
    ]
