# Generated by Django 5.2.14 on 2026-05-28 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_bet_id_alter_game_id_alter_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roulettebet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto recargado')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo antes')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo después')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('failed', 'Fallido')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de recarga')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas internas')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='games.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-created_at'],
            },
        ),
    ]
